"01": "Статья в сериальном издании"
"02": "Отдельный выпуск журнала"
"03": "Статья в сборнике депонированных научных работ"
"04": "Статья в книге, сборнике"
"05": "Книга"
"06": "Проспект (проспект, каталог)"
"08": "Депонированная научная работа – монография, сборник"
"09": "Патентный документ"
"10": "Нормативные документы"
"11": "Диссертационные работы (диссертации, авторефераты)"
"14": "Картографические издания (атласы, карты)"

