1: Индивидуальный автор
2: Перевод основного заглавия на русский язык
3: Заглавие издания при описании статей
4: Язык основного текста документа
5: Отражение реферативными службами
6: Ключевое слово
7: Дата издания депонирования
11: Составитель
12: Заявитель (патентовладелец) изобретения
13: Редактор
15: Оснащение документа библиографическими ссылками
16: Параллельное заглавие издания
17: Номер депонирования
18: Вид патентного документа
21: Основное заглавие
22: Сокращенное наименование коллективного автора издания; организации - депонента
23: Заглавие тома, выпуска или части многотомника
24: Обозначение части статьи
25: Заглавие части статьи
29: Номер специальности
30: Место издания – город II
31: Параллельное заглавие издания при описании статей
32: Издательство II
33: Издательство I
35: Вид документа (двухсимвольный)
#Записывается двухсимвольный цифровой код вида документа, принятый в ВИНИТИ (см. раздел 4).
36: Код рубрики рубрикатора ВИНИТИ
#Записывается в виде группы цифр со следующей структурой: ХХХ.ХХ.ХХ...
#Максимальное количество уровней - 9, минимальное - 2.
#Каждый код рубрики записывается в отдельном поле.
#Несколько значений разделяются знаком %
37: Индекс УДК
#Записывается в виде, присвоенном при обработке документа.
#Несколько значений разделяются знаком %
38: Заглавие несамостоятельного приложения сериального издания
#Записывается  сокращенное слово “прил.”  на русском языке  и сведения
#о приложении на языке оригинала в сокращенном виде.
40: Страна подачи заявки изобретения
#Записывается на русском языке название страны или патентного ведомства,
#опубликовавшего документ.
41: Язык вспомогательного текста
#Способ и пример записи приведены в элементе данных “Язык основного
#текста документа” (метка 004).
42: Место издания (страна)
#Записывается двухбуквенный  код страны [1] на латинице,
#на территории которой издан документ.
43: Объем, пагинация
#Записывается римскими и/или арабскими цифрами или буквенными обозначениями,
#как дано на документе,  и с сокращенным словом с.  (страницы) на русском языке.
#При отсутствии нумерации страниц, их просчитывают и приводят в квадратных скобках.
#Несколько значений разделяются знаком %
44: Оснащение документа иллюстративным материалом
#Записывается количество арабскими цифрами и обозначение на русском языке
#ил. и/или  табл. цифрами и/или  карт(а,ы).
46: Страна или город – место издания
#Приводится на языке оригинала без сокращения название издающей страны или
#название города. Для документов с особой графикой письма названия приводится
#на русском языке.
47: Сведения, относящиеся к заглавию
#Записывается в виде, приведенном на документе. Сокращения слов и
#словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12. применяют для сведений
#о жанре документа, посвящении и т.п.
48: Место издания – город I
#Записывается, как правило, название города в виде, приведенном на документе.
#Сокращаются названия только четырех городов:
#Москва (М.), Ленинград (Л.), Санкт-Петербург (С.-Пб) и Ростов-на-Дону (Ростов-н/Д).
#Если на документе указано два места издания, то второе записывается в
#отдельном поле с меткой.030 Если на документе указано более двух мест издания,
#записывают первое со словами “и др.” для документов с кириллическим алфавитом и
#“etc.” для документов с латинским алфавитом. К названию города могут быть
#добавлены в скобках уточняющие сведения (напр. сокращение названий штатов США,
#области, страны и т.д.). При отсутствии на документе места издания
#(или места печатания) приводят сокращенные слова “Б.м.” (Без места)
#для документов с кириллическим алфавитом и “S.l.” (Sine loko) для документов
#с латинским алфавитом. Для документов с особой графикой письма  названия города
#приводят на русском языке.
49: Оснащение документа вспомогательным текстом
#Записывается сокращенное слово прил. на русском языке и в круглых скобках
#количество страниц, на которых размещен сопроводительный материал.
52: ISSN
#Записывается в виде двух четырехзначных цифровых групп, разделенных знаком дефис.
#Цифры арабские от 0 до 9. Последняя цифра (контрольная) может быть
#римской цифрой десять. Если на документе присутствует два ISSN,
#то второе значение записывается в поле с меткой 068.
53: ISBN
#Записывается десять цифр, разделенных на четыре группы цифр различной длины
#дефисом или пробелом или иным способом. Цифры арабские от 0 до 9.
#Последняя цифра может быть римской цифрой десять.
#Если на документе присутствует два ISBN,то второе значение
#записывается в поле с меткой 067.
54: Том, выпуск или часть многотомника
#Записывается сокращенным словом, обозначающим том или часть многотомника
#на языке оригинала и буквенного или цифрового обозначения тома или части тома.
#Сокращение слов производится в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
#Числовые данные записываются арабскими цифрами.
#Несколько значений разделяются знаком %
59: Сведения, относящиеся к заглавию издания при описании статей
#Записывают в сокращено или в полном виде (с    г. для статей из книг и
#депонированных работ).
61: Дата депонирования работы
#Способ и пример записи приведены в элементе данных “Дата приоритета” (метка 086).
62: Организация - место защиты диссертации
#Записывается наименование организации и город, где была защищена
#диссертация. Наименование организации приводится на языке оригинала с
#сокращением слов и словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
#Название города не сокращается.
63: Сокращение оригинального заглавия вброшюрованного журнала
#Записывается в сокращенном виде основное заглавие вброшюрованного
#журнала в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
65: Часть тома или выпуска многотомника
#Способ и пример записи приведены в элементе данных “Том, выпуск или
#часть многотомника” (метка 054).
67: ISBN II
#Способ записи приведен в элементе данных ISBN I (метка 053)
68: ISSN II
#Способ записи приведен в элементе данных ISSN I (метка 052)
69: Том сериального издания для вброшюрованного журнала
#Записывается том вброшюрованного журнала. Способ и пример записи приведены
#в элементе данных “Том сериального издания” (метка 074).
70: Заглавие части тома или выпуска многотомника
#Способ и пример записи приведены в элементе данных “Заглавие тома,
#выпуска или части многотомника” (метка 023).
72: Обозначение и номер подсерии
#Записывается обозначение подсерии в виде, данном на документе,
#затем номер подсерии в виде буквы, арабской цифры или буквенно-цифрового
#обозначения. Слово, обозначающее понятие “серия”:
#а) записывают в сокращенном виде;
#б) не приводят, если за ним следует буквенное обозначение подсерии.
73: Номер выпуска для вброшюрованного журнала
#Способ и пример записи приведены в элементе данных “Номер выпуска
#сериального издания” (метка 076).
74: Том сериального издания
#Записывается цифровое или буквенно-цифровое обозначение тома сериального
#издания без слов, обозначающих том. Если том установлен по другим источникам,
#он приводится в квадратных скобках. С восклицательным знаком в квадратных
#скобках – в том случае, если значение тома ошибочно. Несколько значений
#разделяются знаком %
75: Заглавие серии (для книг, карт, атласов)
#Записываются в сокращенном виде основное заглавие серии, сведения, относящиеся
#к заглавию серии, сведения об ответственности, ISSN серии, номер части тома или
#выпуска. Сокращение слов и словосочетаний производится в соответствии с
#ГОСТ 7.11 и ГОСТ 7.12. Разделительные знаки между элементами записывают
#по правилам библиографического описания.
76: Номер выпуска сериального издания
#Записывается цифровое, буквенное или буквенно-цифровое обозначение номера
#сериального издания. Если вместо номера указан месяц или число и месяц,
#или сезон, то запись производится с сокращением слов на языке оригинала.
#Если номер выпуска установлен по другим источникам, он приводится в квадратных
#скобках. Если номер ошибочный, он приводится с восклицательным знаком
#в квадратных скобках.
77: Часть номера выпуска сериального издания
#Записывается русская прописная буква Ч. (часть) и цифровое или
#буквенное значение части номера Несколько значений разделяются знаком %.
78: Дата защиты диссертации (год)
#Записывается год защиты диссертации в виде ГГГГ.
79: Обозначение нормативного документа
#Записывается в виде, приведенном на документе. При описании сборников
#стандартов допускается или перечисление через запятую не более 3 обозначений,
#или интервал обозначений через дефис.
#В круглых скобках приводится обозначение стандартов, которым соответствует данный.
83: Дата подачи заявки изобретения
#Способ и пример записи приведены в элементе данных “Дата приоритета” (метка 086).
84: Место депонирования
#Записывается наименование организации (учреждения) -депозитария в сокращенном виде
86: Дата приоритета
#Записывается арабскими цифрами в виде:
#ДД.ММ.ГГГГ, где
#ДД - число;
#ММ – месяц;
#ГГГГ – год
90: Индекс МПК
#Записываются два первых класса МПК. Перед обозначением индекса (или после)
#в фигурных скобках указывается редакция (год) МПК.
#Несколько значений разделяются знаком %.
91: Ученая степень
#Сведения об ученой степени записывают на языке оригинала с сокращением
#слов и словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
92: Номер патентного документа
#Записывается слитно без дефиса, запятых, точек или пробелов между
#цифрами, а также без знака № и букв, стоящих перед и после цифр.
93: Сведения о переиздании
#Записывается сокращенно на русском языке в соответствии с ГОСТ 7.11.
94: Регистрационный номер заявки - неформализованный
#Записывается без запятых, пробелов и букв, стоящих перед ним.
#Исключение: для международных заявок РСТ записываются буквы,
#стоящие перед числовыми данными.
95: Дата публикации заявки изобретения
#Способ записи приведен в элементе данных “Дата приоритета” (метка 086).
96: Местонахождение (город) организации - депонента
#Записывается название города без сокращения. Исключение:
#Москва - М.; Ленинград - Л.; Санкт-Петербург - Спб.;
#Ростов-на-Дону - Ростов-н/Д.
97: Страна приоритета
#Записывается на русском языке название страны, в которой была впервые
#подана заявка на изобретение, патент.
98: Номер приоритетной заявки - неформализованный
#Записывается в виде, приведенном на документе.
99: Индекс НПК
#Записывается первый класс НПК в виде, приведенном на документе.
#Для патентов Великобритании указываются только три первых знака.
100: Реферат
#Записывается в соответствии с ГОСТ 7.9 и инструкциями ВИНИТИ.
202: Заглавие подсерии
#Записывают в виде, приведенном на документе. Для документов с особой
#графикой письма записывают в латинской транслитерации.
210: Часть номера сериального издания для вброшюрованного журнала
#Способ и пример записи приведены в элементе данных “Часть номера
#выпуска сериального издания” (метка 077).
219: Место выполнения работы
#Записывается наименование учреждения, страны, населенного пункта
#(адрес выполнения работы или адрес для связи)
501: Имя (шифр) выпуска базы данных ВИНИТИ
#Записывается четырехсимвольный шифр выпуска базы данных ВИНИТИ,
#где два первых символа – латинские буквы,обозначающие префикс
#тематического фрагмента БД, а два последних – цифровой код выпуска БД.
504: Коды рубрики рубрикатора ГРНТИ
#Записывается в виде группы арабских цифр со следующей структурой:
#ХХ.ХХ.ХХ. Несколько значений разделяются знаком %.
507: Номер выпуска РЖ и БД
#Записывается порядковый номер выпуска (в пределах года) информационного
#продукта (БД/РЖ) ВИНИТИ.
514: Имя (шифр) тематического фрагмента БД ВИНИТИ
#Записывается двухсимвольный шифр тематического фрагмента базы данных
#ВИНИТИ,год генерации БД и организация – создатель БД.
