AB: Автоматика и радиоэлектроника
AB00: Автоматика и радиоэлектроника
AB01: Автоматика и телемеханика
AB02: Вычислительные машины и системы

AB05: Материалы для микро- и наноэлектроники
AB06: Техническая кибернетика
AB08: Программное обеспечение
AB09: Проектирование, конструирование, технология и оборудование для радиотехнического производства
AB10: Радиолокация. Радионавигация. Радиоуправление. Телевизионная техника
AB11: Радиопередающие и радиоприёмные устройства. Запись и воспроизведение сигналов. Радиотехнические измерения.
AB12: Теоретическая радиотехника. Антенны. Волноводы. Обёмные резонаторы. Распространение радиоволн
AB14: Радиосвязь, радиовещание, телевидение
AB15: Сети и системы связи
AB16: Квантовая электроника. Криоэлектроника. Голография
AB17: Волоконно-оптическая cвязь
AB18: Метрология и измерительная техника
AB21: Электровакуумные и твердотельные приборы.

AC: Астрономия
AC00: Астрономия
AC01: Астрономия
AC02: Геодезия и аэросъемка
AC03: Исследование Земли из космоса
AC04: Исследование космического пространства
BI: Биология
BI00: Биология
BI02: Почвоведение и агрохимия
BI03: Растениеводство (Биологические основы)
BI04: Фитопатология
BI05: Биология сельскохозяйственных животных
BI06: Лесоведение и лесоводство
BI07: Общие проблемы биологии
BI10: Общая экология. Биоценология. Гидробиология
BI11: Вирусология
BI12: Микробиология общая
BI13: Микробиология прикладная
BI14: Микробиология санитарная и медицинская
BI15: Ботаника (Водоросли. Грибы. Лишайники)
BI16: Физиология и биохимия растений
BI17: Зоология общая. Зоология беспозвоночных
BI19: Ихтиология
BI20: Энтомология
BI21: Зоопаразитология
BI23: Физиология человека и животных (Кровь. Лимфа Кровообращение. Дыхание. Почки)
BI24: Физиология человека и животных (Нейрофизиология. Сенсорные системы. Высшая нервная деятельность. Нервно-мышечная система)
BI25: Физиология человека и животных (Общие проблемы. Возрастная физиология. Прикладная физиология. Терморегуляция)
BI26: Физиология человека и животных (Обмен веществ. Питание. Пищеварение)
BI27: Физиология человека и животных. (Эндокринная система. Размножение. Лактация)
BI28: Онкология (Терапия опухолей)
BI29: Онкология экспериментальная
BI30: Онкология клиническая
BI31: Клиническая фармакология
BI34: Токсикология
BI35: Наркологическая токсикология
BI36: Радиационная биология
BI38: Бионика. Биокибернетика. Биоинженерия
BI39: Иммунология. Аллергология
BI40: Общие вопросы патологической анатомии
BI41: Ботаника (Высшие растения)
BI44: Психология
BI45: Зоология наземных позвоночных (Общие вопросы. Герпетология)
BI46: Зоология наземных позвоночных (Орнитология)
BI47: Зоология наземных позвоночных (Териология. Охотоведение. Зоопарки)
BI48: Фармакология общая. Химиотерапевтические средства
BI49: Морфология и цитология человека и животных. Антропология.


VN: Вычислительные науки
VN00: Вычислительные науки

GE: Генетика
GE00: Генетика
GE01: Общая генетика
GE02: Генетика и селекция возделываемых растений
GE03: Генетика и селекция микроорганизмов
GE04: Генетика человека
GE05: Генетика и селекция сельскохозяйственных животных

GG: География
GG00: География
GG01: Биогеография. География почв
GG02: География Америки,Австралии,Океании и Антарктики
GG03: География зарубежной Азии и Африки
GG04: География зарубежной Европы
GG06: Картография
GG07: Теоретические и общие вопросы географии
GG08: Медицинская география
GG09: География Российской Федерации

GL: Геология
GL00: Геология
GL01: Oбщая геология
GL02: Стратиграфия. Палеонтология
GL03: Антропогеновый период. Геоморфология суши и морского дна
GL04: Геологические и геохимические методы поисков полезных ископаемых. Методы разведки и оценка месторождений. Разведочная и промысловая геофизика
GL05: Месторождения горючих полезных ископаемых
GL06: Неметаллические полезные ископаемые
GL07: Рудные месторождения
GL08: Tехника геолого-разведочных работ
GL09: Геохимия. Минералогия. Петрография
GL10: Гидрогеология. Инженерная геология. Мерзлотоведение


GF: Геофизика
GF00: Геофизика
GF01: Геомагнетизм и высокие слои атмосферы
GF02: Метеорология и климатология
GF03: Океанология. Гидрология суши. Гляциология
GF04: Физика Земли


GD: Горное дело
GD00: Горное дело
GD01: Обогащение полезных ископаемых
GD02: Общие вопросы горного дела
GD05: Разработка нефтяных и газовых месторождений
GD06: Разработка месторождений твердых полезных ископаемых


IP: Издательское дело и полиграфия
IP00: Издательское дело и полиграфия

IN: Информатика
IN00: Информатика

KR: Коррозия и защита от коррозии
KR00: Коррозия и защита от коррозии

LR: Лекарственные растения
LR00: Лекарственные растения

MA: Математика
MA00: Математика
MA01: Общие вопросы математики. Математическая логика. Теория чисел. Алгебра. Топология. Геометрия
MA02: Математический анализ
MA03: Теория вероятностей и математическая статистика
MA04: Вычислительная математика. Математическая кибернетика


MH: Машиностроение
MH00: Машиностроение
MH01: Робототехника
MH02: Тракторы и сельскохозяйственные машины и орудия
MH03: Химическое, нефтеперерабатывающее и полимерное машиностроение
MH04: Вопросы технического поргресса и организации производства в машиностроении
MH05: Оборудование пищевой промышленности
MH07: Резание материалов. Станки и инструменты
MH08: Технология и оборудование кузнечно-штамповочного производства
MH09: Технология и оборудование литейного производства
MH10: Технология и оборудование механо-сборочного производства
MH14: Технология и оборудование лесозаготовительного, деревообрабатывающего и целлюлозно-бумажного производства
MH15: Машиностроительные материалы, конструкции и расчет деталей машин. Гидропривод
MH16: Коммунальное, бытовое и торговое оборудование
MH17: Горное и нефтепромысловое машиностроение
MH18: Насосостроение и компрессоростроение. Холодильное машиностроение
MH19: Строительные и дорожные машины
MH20: Авиационные и ракетные двигатели
MH21: Ракетостроение и космическая техника
MH22: Двигатели внутреннего сгорания
MH24: Tурбостроение.Котлостроение
MH25: Автомобилестроение
MH26: Судостроение
MH27: Авиастроение
MH28: Локомотивостроение и вагоностроение
MH29: Подъемно-транспортное машиностроение
MH30: Лёгкая промышленность

MD: Медицина
MD00: Медицина

MT: Металлургия
MT00: Металлургия
МТ01: Металловедение и термическая обработка
МТ02: Порошковая металлургия. Наноматериалы. Покрытия и пленки, получаемые физико-металлургическими методами
МТ03: Производство чугуна и стали
МТ04: Теория металлургических процессов
МТ05: Прокатное и волочильное производство
МТ07: Металлургическая теплотехника. Оборудование, измерение, контроль и автоматизация в металлургическом производстве
МТ08: Металлургия цветных металлов

MX: Механика
MX00: Механика
MX01: Общие вопросы механики. Общая механика
MX02: Механика жидкости и газа
MX03: Комплексные и специальные разделы механики
MX04: Механика деформируемого твердого тела
MX05: Прочность конструкций и материалов

EX: Экономика промышленности
EX00: Экономика промышленности
EX01: Пожарная охрана
EX03: Риск и безопасность.


OC: Охрана окружающей среды
OC00: Охрана окружающей среды
OC01: Охрана природы и воспроизводство природных ресурсов
ОС02: Экология человека
OC03: Системы, приборы и методы контроля качества окружающей среды
ОС04: Охрана и улучшение городской среды
OC05: Технологические аспекты охраны окружающей среды


POLY: Политематическая база данных
POLY00: Политематическая база данных

CB: Сварка
CB00: Сварка

TR: Транспорт
TR00: Транспорт
TR01: Техническая эксплуатация подвижного состава и тяга поездов
TR02: Управление перевозочным процессом на железных дорогах
TR03: Строительство железных дорог. Путь и путевое хозяйство
TR04: Автоматика, телемеханика и связь на железных дорогах
TR05: Автомобильный транспорт
TR06: Городской транспорт
TR07: Взаимодействие разных видов транспорта, логистика и контейнерные перевозки
TR10: Водные перевозки. Техническая эксплуатация и ремонт флота
TR11: Транспорт промышленных предприятий. Логистика. Склады, автоматизация погрузочно-разгрузочных работ
TR15: Организация и безопасность дорожного движения
TR16: Трубопроводный транспорт
TR19: Автомобильные дороги
TR20: Воздушный транспорт. Аэропорты.


FI: Физика
FI00: Физика
FI01: Акустика
FI02: Оптика и лазерная физика
FI03: Радиофизика и физические основы электроники
FI05: Физика газов и жидкостей. Термодинамика и статистическая физика
FI06: Ядерная физика и физика ядерных реакторов
FI07: Физика Элементарных частиц и теория полей
FI08: Физика плазмы
FI09: Физика твердых тел (Структура и динамика решетки)
FI10: Общие вопросы физики и физического эксперимента
FI15: Физика твердых тел (Электрические свойства)
FI16: Физика твердых тел (Магнитные свойства)
FI17: Сверхпроводимость
FI18: Спинтроника
FI19: Физика нанообъектов и нанотехнология


FB: Физико-химическая биология и биотехнология
FB00: Физико-химическая биология и биотехнология
FB01: Биохимия
FB03: Молекулярная биология
FB04: Биофизика
FB05: Молекулярная и клеточная иммунология
FB06: Биотехнология. Бионанотехнология. Бионаноматериалы


CH: Химия
CH00: Химия
CH01: Аналитическая химия. Оборудование лаборатории
CH02: Неорганическая химия. Комплексные соединения. Радиохимия
CH03: Общие вопросы химии. Физическая химия (Строение молекул)
CH04: Общие вопросы химической технологии
CH05: Органическая химия
CH06: Природные органические соединения и их синтетические аналоги
CH07: Технология силикатных и тугоплавких неметаллических материалов
CH08: Технология неорганических веществ и материалов
CH09: Технология органических веществ
CH10: Технология органических лекарственных веществ, ветеринарных препаратов и пестицидов
CH11: Технология полимерных материалов (Пластмассы. Иономенные материалы)
CH12: Технология полимерных материалов (Природные высокомолекулярные соединения. Химия и переработка древесины. Химические волокна. Текстильные материалы. Бумага. Кожа. Мех)
CH13: Технология полимерных материалов (Резина. Лакокрасочные материалы и органические покрытия. Вспомогательные материалы для производства полимеров и изделий из них)
CH14: Физическая химия (Кинетика. Катализ. Фотохимия. Радиационная химия. Плазмохимия)
CH15: Физическая химия (Кристаллохимия. Химия твердого тела. Газы. Жидкости. Аморфные тела. Поверхностные явления. Химия коллоидов)
CH16: Физическая химия (Химическая термодинамика. Физико-химический анализ.Растворы. Электрохимия)
CH17: Химия высокомолекулярных соединений
CH18: Химия и переработка горючих ископаемых и природных газов
CH19: Химия и технология пищевых продуктов
CH20: Технология производства продуктов бытовой химии. Парфюмерия и косметика


EK: Экономика промышленности
EK00: Экономика промышленности
EK01: Мировая экономика. Социально-экономическое развитие стран мира
EK02: Применение математических методов в экономических исследованиях и планировании
EK03: Кадры (Подбор. Подготовка. Эффективность использования). Экономика образования
EK04: Общеотраслевые вопросы совершенствования хозяйственного механизма
EK05: Экономика отраслей металлургического и машиностроительного комплексов
EK06: Экономика отраслей легкой промышленности
EK07: Методы управления экономикой
EK08: Экономика отраслей топливно-энергетического комплекса
EK09: Экономика отраслей химико-лесного комплекса
EK10: Экономика отраслей пищевой промышленности.
EK11: Научно-технический прогресс. Инновации. Организация и финансирование научно-исследовательских работ
EK12: Экономические аспекты организации и техники систем управления
EK14: Экономика агропромышленного комплекса
EK15: Экономика непроизводственной сферы
EK16: Экономика строительства
EK17: Экономика транспорта, связи и телекоммуникаций
EK18: Финансы. Банки. Страхование

EE: Экономия энергии
EE00: Экономия энергии

EL: Электротехника
EL00: Электротехника
EL01: Общие вопросы и теоретические основы электротехники. Электробезопасность
EL02: Электрические аппараты
EL03: Электрические машины и трансформаторы
EL04: Электротехнические материалы, электрические конденсаторы, провода и кабели
EL05: Силовая преобразовательная техника
EL06: Электропривод и автоматизация промышленных установок
EL07: Электротехнология
EL08: Электрооборудование транспорта
EL11: Светотехника и инфракрасная техника


EN: Энергетика
EN00: Энергетика
EN01: Атомная энергетика
EN02: Общие вопросы энергетики. Энергетический баланс. Топливо
EN03: Электрические станции и сети
EN04: Энергетические системы и их автоматизация
EN05: Теоретические основы теплотехники. Промышленная теплотехника
EN06: Тепловые электростанции. Теплоснабжение
EN07: Котельные установки и водоподготовка
EN08: Генераторы прямого преобразования тепловой и химической энергии в электрическую
EN09: Гидроэнергетика
EN11: Нетрадиционные и возобновляемые источники энергии
EN12: 
