topic:
  AB: "Автоматика и радиоэлектроника"
  AB01: "Автоматика и телемеханика"
  AB02: "Вычислительные машины и системы"
  AB03: "Электровакуумные и газоразрядные приборы и устройства"
  AB04: "Полупроводниковые приборы"
  AB05: "Материалы для электроники"
  AB06: "Техническая кибернетика"
  AB07: "Оптоэлектронные приборы"
  AB08: "Программное обеспечение"
  AB09: "Проектирование, конструирование, технология и оборудование для радиотехнического производства"
  AB10: "Радиолокация. Радионавигация. Радиоуправление. Телевизионная техника"
  AB11: "Радиопередающие и радиоприемные устройства. Радиотехнические измерения"
  AB12: "Теоретическая радиотехника. Антенны. Волноводы. Об'емные резонаторы. Распространение радиоволн"
  AB13: "Электроакустика. Запись и воспроизведение сигналов"
  AB14: "Радиосвязь, радиовещание, телевидение"
  AB15: "Сети и системы связи"
  AB16: "Квантовая электроника. Криоэлектроника. Голография"
  AB17: "Волоконно-оптическая звязь"
  AB18: "Метрология и измерительная техника"
  AB20: "Электровакуумные и твердотельные приборы.Приборы микро- и наноэлектроники"

  BI: "Биология"
  BI02: "Почвоведение и агрохимия"
  BI03: "Растениеводство (Биологические основы)"
  BI04: "Фитопатология"
  BI05: "Биология сельскохозяйственных животных"
  BI06: "Лесоведение и лесоводство"
  BI07: "Общие проблемы биологии"
  BI10: "Общая экология. Биоценология. Гидробиология"
  BI11: "Вирусология"
  BI12: "Микробиология общая"
  BI13: "Микробиология прикладная"
  BI14: "Микробиология санитарная и медицинская"
  BI15: "Ботаника (Водоросли. Грибы. Лишайники)"
  BI16: "Физиология и биохимия растений"
  BI17: "Зоология общая. Зоология беспозвоночных"
  BI19: "Ихтиология"
  BI20: "Энтомология"
  BI21: "Зоопаразитология"
  BI23: "Физиология человека и животных (Кровь. Лимфа Кровообращение. Дыхание. Почки)"
  BI24: "Физиология человека и животных (Нейрофизиология. Сенсорные системы. Высшая нервная деятельность. Нервно-мышечная система)"
  BI25: "Физиология человека и животных (Общие проблемы. Возрастная физиология. Прикладная физиология. Терморегуляция)"
  BI26: "Физиология человека и животных (Обмен веществ. Питание. Пищеварение)"
  BI27: "Физиология человека и животных. (Эндокринная система. Размножение. Лактация)"
  BI28: "Онкология (Терапия опухолей)"
  BI29: "Онкология экспериментальная"
  BI30: "Онкология клиническая"
  BI31: "Клиническая фармакология"
  BI34: "Токсикология"
  BI35: "Наркологическая токсикология"
  BI36: "Радиационная биология"
  BI38: "Бионика. Биокибернетика. Биоинженерия"
  BI39: "Иммунология. Аллергология"
  BI40: "Общие вопросы патологической анатомии"
  BI41: "Ботаника (Высшие растения)"
  BI44: "Психология"
  BI45: "Зоология наземных позвоночных (Общие вопросы. Герпетология)"
  BI46: "Зоология наземных позвоночных (Орнитология)"
  BI47: "Зоология наземных позвоночных (Териология. Охотоведение. Зоопарки)"
  BI48: "Фармакология общая. Химиотерапевтические средства"
  BI49: "Морфология и цитология человека и животных. Антропология."

  AC: "Астрономия"
  AC01: "Астрономия"
  AC02: "Геодезия и аэросъемка"
  AC03: "Исследование Земли из космоса"
  AC04: "Исследование космического пространства"

  IN: "Информатика"
  IN00: "Информатика"

  EK: "Экономика промышленности"
  EK01: "Мировая экономика. Социально-экономическое развитие стран мира"
  EK02: "Применение математических методов в экономических исследованиях и планировании"
  EK03: "Кадры (Подбор. Подготовка. Эффективность использования). Экономика образования"
  EK04: "Общеотраслевые вопросы совершенствования хозяйственного механизма"
  EK05: "Экономика отраслей металлургического и машиностроительного комплексов"
  EK06: "Экономика отраслей легкой промышленности"
  EK07: "Методы управления экономикой"
  EK08: "Экономика отраслей топливно-энергетического комплекса"
  EK09: "Экономика отраслей химико-лесного комплекса"
  EK10: "Экономика отраслей пищевой промышленности"
  EK11: "Научно-технический прогресс. Интеграция науки с производством. Организация и финансирование научно-исследовательских работ"
  EK12: "Экономические аспекты организации и техники систем управления"
  EK13: "Проблемы функционирования рыночного хозяйства"
  EK14: "Экономика агропромышленного комплекса"
  EK15: "Экономика непроизводственной сферы"
  EK16: "Экономика строительства"
  EK17: "Экономика транспорта, связи и телекоммуникаций"

  EL: "Электротехника"
  EL00: "Электротехника"
  EL01: "Общие вопросы и теоретические основы электротехники. Электробезопасность"
  EL02: "Электрические аппараты"
  EL03: "Электрические машины и трансформаторы"
  EL04: "Электротехнические материалы, электрические конденсаторы, провода и кабели"
  EL05: "Силовая преобразовательная техника"
  EL06: "Электропривод и автоматизация промышленных установок"
  EL07: "Электротехнология"
  EL08: "Электрооборудование транспорта"
  EL09: "Электрофикация быта"
  EL11: "Светотехника и инфракрасная техника"

  FI: "Физика"
  FI01: "Акустика"
  FI02: "Оптика и лазерная физика"
  FI03: "Радиофизика и физические основы электроники"
  FI04: "Физика атома и молекулы"
  FI05: "Физика газов и жидкостей. Термодинамика и статистическая физика"
  FI06: "Ядерная физика и физика ядерных реакторов"
  FI07: "Физика Элементарных частиц и теория полей"
  FI08: "Физика плазмы"
  FI09: "Структура и динамика решетки твердых тел"
  FI10: "Общие вопросы физики и физического эксперимента"
  FI15: "Электрические свойства твердых тел"
  FI16: "Магнитные свойства твердых тел"
  FI17: "Сверхпроводимость"
  FI18: "Спинтроника"
  FI19: "Физика нанообъектов и нанотехнология"

codes_documents:
  01: "Статья в сериальном издании"
  02: "Отдельный выпуск журнала"
  03: "Статья в сборнике депонированных научных работ"
  04: "Статья в книге, сборнике"
  05: "Книга"
  06: "Проспект (проспект, каталог)"
  08: "Депонированная научная работа – монография, сборник"
  09: "Патентный документ"
  10: "Нормативные документы"
  11: "Диссертационные работы (диссертации, авторефераты)"
  14: "Картографические издания (атласы, карты)"

code1: Индивидуальный автор
code2: Перевод основного заглавия на русский язык
code3: Заглавие издания при описании статей
code4: Язык основного текста документа
code5: Отражение реферативными службами
code6: Ключевое слово
code7: Дата издания депонирования
code11: Составитель
code12: Заявитель (патентовладелец) изобретения
code13: Редактор
code15: Оснащение документа библиографическими ссылками
code16: Параллельное заглавие издания
code17: Номер депонирования
code18: Вид патентного документа
code21: Основное заглавие
code22: Сокращенное наименование коллективного автора издания; организации - депонента
code23: Заглавие тома, выпуска или части многотомника
code24: Обозначение части статьи
code25: Заглавие части статьи
code29: Номер специальности
code30: Место издания – город II
code31: Параллельное заглавие издания при описании статей
code32: Издательство II
code33: Издательство I
code35: Вид документа (двухсимвольный)
#Записывается двухсимвольный цифровой код вида документа, принятый в ВИНИТИ (см. раздел 4).
code36: Код рубрики рубрикатора ВИНИТИ
#Записывается в виде группы цифр со следующей структурой: ХХХ.ХХ.ХХ...
#Максимальное количество уровней - 9, минимальное - 2.
#Каждый код рубрики записывается в отдельном поле.
#Несколько значений разделяются знаком %
code37: Индекс УДК
#Записывается в виде, присвоенном при обработке документа.
#Несколько значений разделяются знаком %
code38: Заглавие несамостоятельного приложения сериального издания
#Записывается  сокращенное слово “прил.”  на русском языке  и сведения
#о приложении на языке оригинала в сокращенном виде.
code40: Страна подачи заявки изобретения
#Записывается на русском языке название страны или патентного ведомства,
#опубликовавшего документ.
code41: Язык вспомогательного текста
#Способ и пример записи приведены в элементе данных “Язык основного
#текста документа” (метка 004).
code42: Место издания (страна)
#Записывается двухбуквенный  код страны [1] на латинице,
#на территории которой издан документ.
code43: Объем, пагинация
#Записывается римскими и/или арабскими цифрами или буквенными обозначениями,
#как дано на документе,  и с сокращенным словом с.  (страницы) на русском языке.
#При отсутствии нумерации страниц, их просчитывают и приводят в квадратных скобках.
#Несколько значений разделяются знаком %
code44: Оснащение документа иллюстративным материалом
#Записывается количество арабскими цифрами и обозначение на русском языке
#ил. и/или  табл. цифрами и/или  карт(а,ы).
code46: Страна или город – место издания
#Приводится на языке оригинала без сокращения название издающей страны или
#название города. Для документов с особой графикой письма названия приводится
#на русском языке.
code47: Сведения, относящиеся к заглавию
#Записывается в виде, приведенном на документе. Сокращения слов и
#словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12. применяют для сведений
#о жанре документа, посвящении и т.п.
code48: Место издания – город I
#Записывается, как правило, название города в виде, приведенном на документе.
#Сокращаются названия только четырех городов:
#Москва (М.), Ленинград (Л.), Санкт-Петербург (С.-Пб) и Ростов-на-Дону (Ростов-н/Д).
#Если на документе указано два места издания, то второе записывается в
#отдельном поле с меткой.030 Если на документе указано более двух мест издания,
#записывают первое со словами “и др.” для документов с кириллическим алфавитом и
#“etc.” для документов с латинским алфавитом. К названию города могут быть
#добавлены в скобках уточняющие сведения (напр. сокращение названий штатов США,
#области, страны и т.д.). При отсутствии на документе места издания
#(или места печатания) приводят сокращенные слова “Б.м.” (Без места)
#для документов с кириллическим алфавитом и “S.l.” (Sine loko) для документов
#с латинским алфавитом. Для документов с особой графикой письма  названия города
#приводят на русском языке.
code49: Оснащение документа вспомогательным текстом
#Записывается сокращенное слово прил. на русском языке и в круглых скобках
#количество страниц, на которых размещен сопроводительный материал.
code52: ISSN
#Записывается в виде двух четырехзначных цифровых групп, разделенных знаком дефис.
#Цифры арабские от 0 до 9. Последняя цифра (контрольная) может быть
#римской цифрой десять. Если на документе присутствует два ISSN,
#то второе значение записывается в поле с меткой 068.
code53: ISBN
#Записывается десять цифр, разделенных на четыре группы цифр различной длины
#дефисом или пробелом или иным способом. Цифры арабские от 0 до 9.
#Последняя цифра может быть римской цифрой десять.
#Если на документе присутствует два ISBN,то второе значение
#записывается в поле с меткой 067.
code54: Том, выпуск или часть многотомника
#Записывается сокращенным словом, обозначающим том или часть многотомника
#на языке оригинала и буквенного или цифрового обозначения тома или части тома.
#Сокращение слов производится в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
#Числовые данные записываются арабскими цифрами.
#Несколько значений разделяются знаком %
code59: Сведения, относящиеся к заглавию издания при описании статей
#Записывают в сокращено или в полном виде (с 2001 г. для статей из книг и
#депонированных работ).
code61: Дата депонирования работы
#Способ и пример записи приведены в элементе данных “Дата приоритета” (метка 086).
code62: Организация - место защиты диссертации
#Записывается наименование организации и город, где была защищена
#диссертация. Наименование организации приводится на языке оригинала с
#сокращением слов и словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
#Название города не сокращается.
code63: Сокращение оригинального заглавия вброшюрованного журнала
#Записывается в сокращенном виде основное заглавие вброшюрованного
#журнала в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
code65: Часть тома или выпуска многотомника
#Способ и пример записи приведены в элементе данных “Том, выпуск или
#часть многотомника” (метка 054).
code67: ISBN II
#Способ записи приведен в элементе данных ISBN I (метка 053)
code68: ISSN II
#Способ записи приведен в элементе данных ISSN I (метка 052)
code69: Том сериального издания для вброшюрованного журнала
#Записывается том вброшюрованного журнала. Способ и пример записи приведены
#в элементе данных “Том сериального издания” (метка 074).
code70: Заглавие части тома или выпуска многотомника
#Способ и пример записи приведены в элементе данных “Заглавие тома,
#выпуска или части многотомника” (метка 023).
code72: Обозначение и номер подсерии
#Записывается обозначение подсерии в виде, данном на документе,
#затем номер подсерии в виде буквы, арабской цифры или буквенно-цифрового
#обозначения. Слово, обозначающее понятие “серия”:
#а) записывают в сокращенном виде;
#б) не приводят, если за ним следует буквенное обозначение подсерии.
code73: Номер выпуска для вброшюрованного журнала
#Способ и пример записи приведены в элементе данных “Номер выпуска
#сериального издания” (метка 076).
code74: Том сериального издания
#Записывается цифровое или буквенно-цифровое обозначение тома сериального
#издания без слов, обозначающих том. Если том установлен по другим источникам,
#он приводится в квадратных скобках. С восклицательным знаком в квадратных
#скобках – в том случае, если значение тома ошибочно. Несколько значений
#разделяются знаком %
code75: Заглавие серии (для книг, карт, атласов)
#Записываются в сокращенном виде основное заглавие серии, сведения, относящиеся
#к заглавию серии, сведения об ответственности, ISSN серии, номер части тома или
#выпуска. Сокращение слов и словосочетаний производится в соответствии с
#ГОСТ 7.11 и ГОСТ 7.12. Разделительные знаки между элементами записывают
#по правилам библиографического описания.
code76: Номер выпуска сериального издания
#Записывается цифровое, буквенное или буквенно-цифровое обозначение номера
#сериального издания. Если вместо номера указан месяц или число и месяц,
#или сезон, то запись производится с сокращением слов на языке оригинала.
#Если номер выпуска установлен по другим источникам, он приводится в квадратных
#скобках. Если номер ошибочный, он приводится с восклицательным знаком
#в квадратных скобках.
code77: Часть номера выпуска сериального издания
#Записывается русская прописная буква Ч. (часть) и цифровое или
#буквенное значение части номера Несколько значений разделяются знаком %.
code78: Дата защиты диссертации (год)
#Записывается год защиты диссертации в виде ГГГГ.
code79: Обозначение нормативного документа
#Записывается в виде, приведенном на документе. При описании сборников
#стандартов допускается или перечисление через запятую не более 3 обозначений,
#или интервал обозначений через дефис.
#В круглых скобках приводится обозначение стандартов, которым соответствует данный.
code83: Дата подачи заявки изобретения
#Способ и пример записи приведены в элементе данных “Дата приоритета” (метка 086).
code84: Место депонирования
#Записывается наименование организации (учреждения) -депозитария в сокращенном виде
code86: Дата приоритета
#Записывается арабскими цифрами в виде:
#ДД.ММ.ГГГГ, где
#ДД - число;
#ММ – месяц;
#ГГГГ – год
code90: Индекс МПК
#Записываются два первых класса МПК. Перед обозначением индекса (или после)
#в фигурных скобках указывается редакция (год) МПК.
#Несколько значений разделяются знаком %.
code91: Ученая степень
#Сведения об ученой степени записывают на языке оригинала с сокращением
#слов и словосочетаний в соответствии с ГОСТ 7.11 и ГОСТ 7.12.
code92: Номер патентного документа
#Записывается слитно без дефиса, запятых, точек или пробелов между
#цифрами, а также без знака № и букв, стоящих перед и после цифр.
code93: Сведения о переиздании
#Записывается сокращенно на русском языке в соответствии с ГОСТ 7.11.
code94: Регистрационный номер заявки - неформализованный
#Записывается без запятых, пробелов и букв, стоящих перед ним.
#Исключение: для международных заявок РСТ записываются буквы,
#стоящие перед числовыми данными.
code95: Дата публикации заявки изобретения
#Способ записи приведен в элементе данных “Дата приоритета” (метка 086).
code96: Местонахождение (город) организации - депонента
#Записывается название города без сокращения. Исключение:
#Москва - М.; Ленинград - Л.; Санкт-Петербург - Спб.;
#Ростов-на-Дону - Ростов-н/Д.
code97: Страна приоритета
#Записывается на русском языке название страны, в которой была впервые
#подана заявка на изобретение, патент.
code98: Номер приоритетной заявки - неформализованный
#Записывается в виде, приведенном на документе.
code99: Индекс НПК
#Записывается первый класс НПК в виде, приведенном на документе.
#Для патентов Великобритании указываются только три первых знака.
code100: Реферат
#Записывается в соответствии с ГОСТ 7.9 и инструкциями ВИНИТИ.
code202: Заглавие подсерии
#Записывают в виде, приведенном на документе. Для документов с особой
#графикой письма записывают в латинской транслитерации.
code210: Часть номера сериального издания для вброшюрованного журнала
#Способ и пример записи приведены в элементе данных “Часть номера
#выпуска сериального издания” (метка 077).
code219: Место выполнения работы
#Записывается наименование учреждения, страны, населенного пункта
#(адрес выполнения работы или адрес для связи)
code501: Имя (шифр) выпуска базы данных ВИНИТИ
#Записывается четырехсимвольный шифр выпуска базы данных ВИНИТИ,
#где два первых символа – латинские буквы,обозначающие префикс
#тематического фрагмента БД, а два последних – цифровой код выпуска БД.
code504: Коды рубрики рубрикатора ГРНТИ
#Записывается в виде группы арабских цифр со следующей структурой:
#ХХ.ХХ.ХХ. Несколько значений разделяются знаком %.
code507: Номер выпуска РЖ и БД
#Записывается порядковый номер выпуска (в пределах года) информационного
#продукта (БД/РЖ) ВИНИТИ.
code514: Имя (шифр) тематического фрагмента БД ВИНИТИ
#Записывается двухсимвольный шифр тематического фрагмента базы данных
#ВИНИТИ,год генерации БД и организация – создатель БД.

