chairs:
  aoi:
    1: rsi
    2: rts
    3: tor
    4: svchkr
    5: tu
    6: srs
    7: aoi
    8: asu
    9: ke
    10: tp
    11: pre
    12: ep
    13: fe
    14: fiz
    15: vm
    16: kudr
    17: mguk
    18: isr
    19: kfil
    20: iya
    21: fvis
    22: ks
    23: sps
    24: esau
    25: kibevs
    26: ksup
    27: kipr
    28: kudr
    29: retem
    30: emis
    31: Высший колледж информатики, электроники и менеджмента (ВКИЭМ)          #Неведомая штуковина
    32: Прикладной математики и информатики (ПМИ)                               #Неведомая штуковина
    33: oku
    34: up
    35: gp
    36: ip
    37: ui
    38: es

