rtf:
  name: Радиотехнический факультет
  abbr: РТФ
  chairs:
    rsi:
      name: Кафедра радиоэлектроники и защиты информации
      abbr: РЗИ
    rts:
      name: Кафедра радиотехнических систем
      abbr: РТС
    svchkr:
      name: Кафедра сверхвысокочастотной и квантовой радиотехники
      abbr: СВЧиКР
    tu:
      name: Кафедра телевидения и управления
      abbr: ТУ
    tor:
      name: Кафедра телекоммуникаций и основ радиотехники
      abbr: ТОР
    srs:
      name: Кафедра средств радиосвязи
      abbr: СРС

rkf:
  name: Радиоконструкторский факультет
  abbr: РКФ
  chairs:
    kipr:
      name: Кафедра конструирования и производства радиоаппаратуры
      abbr: КИПР
    kudr:
      name: Кафедра конструирования узлов и деталей РЭС
      abbr: КУДР
    retem:
      name: Кафедра радиоэлектронных технологий и экологического мониторинга
      abbr: РЭТЭМ

fet:
  name: Факультет электронной техники
  abbr: ФЭТ
  chairs:
    fiz:
      name: Кафедра физики
      abbr: Физ.
    pre:
      name: Кафедра промышленной электроники
      abbr: ПрЭ
    fe:
      name: Кафедра физической электроники
      abbr: ФЭ
    ep:
      name: Кафедра электронных приборов и устройств
      abbr: ЭП


fsu:
  name: Факультет систем управления
  abbr: ФСУ
  chairs:
    vm:
      name: Кафедра высшей математики
      abbr: ВМ
    aoi:
      name: Кафедра автоматизации обработки информации
      abbr: АОИ
    asu:
      name: Кафедра автоматизированных систем управления
      abbr: АСУ

fvs:
  name: Факультет вычислительных систем
  abbr: ФВС
  chairs:
    ksup:
      name: Кафедра компьютерных систем в управлении и проектировании
      abbr: КСУП
    kibevs:
      name: Кафедра комплексной информационной безопасности электронно-вычислительных систем
      abbr: КИБЭВС
    esau:
      name: Кафедра электронных средств автоматизации и управления
      abbr: ЭСАУ
    mig:
      name: Кафедра механики и графики
      abbr: МиГ

gf:
  name: Гуманитарный факультет
  abbr: ГФ
  chairs:
    isr:
      name: Кафедра истории и социальной работы
      abbr: ИСР
    fs:
      name: Кафедра философии и социологии
      abbr: ФС
    iya:
      name: Кафедра иностранных языков
      abbr: ИЯ
    sps:
      name: Кафедра спортивного совершенствования по академической гребле
      abbr: СПС
    fvis:
      name: Кафедра физвоспитания и спорта
      abbr: ФВиС

ef:
  name: Экономический факультет
  abbr: ЭФ
  chairs:
    ke:
      name: Кафедра экономики
      abbr: Эконом.
    emis:
      name: Кафедра экономической математики, информатики и статистики
      abbr: ЭМИС

fit:
  name: Факультет инновационных технологий
  abbr: ФИТ
  chairs:
    oku:
      name: Отделение кафедры ЮНЕСКО
      abbr: ОКЮ
    ui:
      name: Кафедра управления инновациями
      abbr: УИ
    es:
      name: Кафедра Электронных систем
      abbr: ЭС

uf:
  name: Юридический факультет
  abbr: ЮФ
  chairs:
    tp:
      name: Кафедра теории права
      abbr: ТП
    up:
      name: Кафедра уголовного права
      abbr: УП
    gp:
      name: Кафедра гражданского права
      abbr: ГП
    ip:
      name: Кафедра информационного права
      abbr: ИП

zivf:
  name: Заочный и вечерний факультет
  abbr: ЗиВФ

vkiem:
  name: Высший колледж информатики, электроники и менеджмента
  abbr: ВКИЭМ
  chairs:
    toe:
      name: Кафедра теоретических основ электротехники
      abbr: ТОЭ

fdo:
  name: Факультет дистанционного обучения
  abbr: ФДО
  chairs:
    kpmii:
      name: Кафедра прикладной математики и информатики
      abbr: КПМиИ

