topic:
  AB01: "Автоматика и вычислительная техника"
  AB02: "Автоматика и вычислительная техника"
  AB08: "Автоматика и вычислительная техника"

  AB09: "Радиотехника"
  AB10: "Радиотехника"
  AB11: "Радиотехника"
  AB12: "Радиотехника"

  AB14: "Связь"
  AB15: "Связь"
  AB17: "Связь"

  AB03: "Электроника"
  AB04: "Электроника"
  AB05: "Электроника"
  AB16: "Электроника"

  AB18: "Метрология и измерительная техника"

  AB06: "Техническая кибернетика"

  AC03: "Исследование земли из космоса"

  IN00: "Информатика"

  EK07: "Организация управления"
  EK12: "Организация управления"

  FI03: "Радиофизика и физические основы электроники"

  EL00: "Электротехника"

codes_documents:
  01: "Статья в сериальном издании"
  02: "Отдельный выпуск журнала"
  03: "Статья в сборнике депонированных научных работ"
  04: "Статья в книге, сборнике"
  05: "Книга"
  06: "Проспект (проспект, каталог)"
  08: "Депонированная научная работа – монография, сборник"
  09: "Патентный документ"
  10: "Нормативные документы"
  11: "Диссертационные работы (диссертации, авторефераты)"
  14: "Картографические издания (атласы, карты)"

