"~:е": "ё"
"~:u": "ü"
" - ": " &ndash; "
'_"': "&#x2032;"
'~"': "&#x2033;"
"_$": "&#x2206;"
"_&": "&#x2193;"
"_'": "&#x2034;"
"_(": "&#x005B;"
"_)": "&#x005D;"
"_*": "&#x00D7;"
"_+": "&#x00B1;"
"_,": "&#x007E;"
"_/": "&#x005F;"
"_1": "&#x201C;"
"_2": "&#x201D;"
"_3": "&#x003C;"
"_4": "&#x003E;"
"_5": "&#x201E;"
"_6": "&#x201D;"
"_7": "&#x223E;"
"_8": "&#x221E;"
"_9": "&#x2205;"
"_:": "&#x007E;"
"_;": "&#x2243;"
"_<": "&#x2264;"
"_=": "&#x2263;"
"_>": "&#x2265;"
"_?": "&#x2030;"
"_?": "&#x2192;"
"_A": "&#x0391;"
"_B": "&#x0392;"
"_C": "&#x03A8;"
"_D": "&#x0394;"
"_E": "&#x0395;"
"_F": "&#x03A6;"
"_G": "&#x0393;"
"_H": "&#x0397;"
"_I": "&#x0399;"
"_J": "&#x05D0;"
"_K": "&#x039A;"
"_L": "&#x039B;"
"_M": "&#x039C;"
"_N": "&#x039D;"
"_O": "&#x039F;"
"_P": "&#x03A0;"
"_Q": "&#x0398;"
"_R": "&#x03A1;"
"_S": "&#x03A3;"
"_T": "&#x03A4;"
"_U": "&#x039E;"
"_W": "&#x03A9;"
"_X": "&#x03A7;"
"_Y": "&#x03A5;"
"_Z": "&#x0396;"
"_a": "&#x03B1;"
"_b": "&#x03B2;"
"_c": "&#x03C8;"
"_d": "&#x03B4;"
"_e": "&#x03B5;"
"_h": "&#x03B7;"
"_i": "&#x03B9;"
"_j": "&#x03B8;"
"_k": "&#x03BA;"
"_l": "&#x03BB;"
"_m": "&#x03BC;"
"_n": "&#x03BD;"
"_o": "&#x03BF;"
"_p": "&#x03C0;"
"_q": "&#x03B3;"
"_r": "&#x03C1;"
"_s": "&#x03C3;"
"_t": "&#x03C4;"
"_u": "&#x03BE;"
"_v": "&#x03C6;"
"_w": "&#x03C9;"
"_x": "&#x03C7;"
"_y": "&#x03C5;"
"_z": "&#x03B6;"
"_|": "&#x2223;"
"~$": "&#x2207;"
"~%": "&#x2260;"
"~&": "&#x2191;"
"~'": "&#x00AE;"
"~(": "&#x007B;"
"~)": "&#x007D;"
"~*": "&#x2297;"
"~+": "&#x2295;"
"~.": "&#x2299;"
"~/": "&#x007E;"
"~5": "&#x20A4;"
"~:": "&#x00F7;"
"~;": "&#x2245;"
"~<": "&#x2272;"
"~=": "&#x2248;"
"~>": "&#x2273;"
"~?": "&#x2190;"
"~?": "&#x2262;"
"~A": "&#x00C6;"
"~B": "&#x00DF;"
"~G": "&#x0152;"
"~H": "&#x21CC;"
"~I": "&#x222B;"
"~K": "&#x220F;"
"~N": "&#x2116;"
"~O": "&#x00D8;"
"~P": "&#x2225;"
"~Q": "&#x2194;"
"~R": "&#x2286;"
"~S": "&#x2287;"
"~T": "&#x22A5;"
"~U": "&#x222A;"
"~V": "&#x221A;"
"~W": "&#x2229;"
"~Y": "&#x2282;"
"~Z": "&#x2283;"
"~a": "&#x00E6;"
"~b": "&#x2122;"
"~c": "&#x00A9;"
"~d": "&#x2202;"
"~e": "&#x2208;"
"~f": "&#x21C4;"
"~g": "&#x0153;"
"~h": "&#x0127;"
"~k": "&#x222E;"
"~l": "&#x0141;"
"~m": "&#x0142;"
"~n": "&#x2209;"
"~o": "&#x00B0;"
"~o": "&#x00F8;"
"~p": "&#x220F;"
"~q": "&#x21D4;"
"~r": "&#x21D2;"
"~s": "&#x2211;"
"~u": "&#x2227;"
"~v": "&#x2228;"
"~w": "&#x00A7;"
"~x": "&#x00B7;"
"~y": "&#x2640;"
"~z": "&#x2642;"
"~|": "&#x005C;"
"%": ", "
"[": "<sub>"
"]": "</sub>"
"{": "<sup>"
"}": "</sup>"
