"{":  "<sup>"
"}":  "</sup>"
"[":  "<sub>"
"]":  "</sub>"
"~:u": "ü"
"_A": "&#x0391;"
"_B": "&#x0392;"
"_G": "&#x0393;"
"_D": "&#x0394;"
"_E": "&#x0395;"
"_Z": "&#x0396;"
"_H": "&#x0397;"
"_Q": "&#x0398;"
"_I": "&#x0399;"
"_K": "&#x039A;"
"_L": "&#x039B;"
"_M": "&#x039C;"
"_N": "&#x039D;"
"_U": "&#x039E;"
"_O": "&#x039F;"
"_P": "&#x03A0;"
"_R": "&#x03A1;"
"_S": "&#x03A3;"
"_T": "&#x03A4;"
"_Y": "&#x03A5;"
"_F": "&#x03A6;"
"_X": "&#x03A7;"
"_C": "&#x03A8;"
"_W": "&#x03A9;"
"_a": "&#x03B1;"
"_b": "&#x03B2;"
"_q": "&#x03B3;"
"_d": "&#x03B4;"
"_e": "&#x03B5;"
"_z": "&#x03B6;"
"_h": "&#x03B7;"
"_j": "&#x03B8;"
"_i": "&#x03B9;"
"_k": "&#x03BA;"
"_l": "&#x03BB;"
"_m": "&#x03BC;"
"_n": "&#x03BD;"
"_u": "&#x03BE;"
"_o": "&#x03BF;"
"_p": "&#x03C0;"
"_r": "&#x03C1;"
"_s": "&#x03C3;"
"_t": "&#x03C4;"
"_y": "&#x03C5;"
"_v": "&#x03C6;"
"_x": "&#x03C7;"
"_c": "&#x03C8;"
"_w": "&#x03C9;"

"~B": "&#x00DF;"
"~A": "&#x00C6;"
"~a": "&#x00E6;"
"~G": "&#x0152;"
"~g": "&#x0153;"
"~h": "&#x0127;"
"~l": "&#x0141;"
"~m": "&#x0142;"
"~O": "&#x00D8;"
"~o": "&#x00F8;"
"_J": "&#x05D0;"
"_(": "&#x005B;"
"_)": "&#x005D;"
"~(": "&#x007B;"
"~)": "&#x007D;"
"_1": "&#x201C;"
"_2": "&#x201D;"
"_3": "&#x003C;"
"_4": "&#x003E;"
"_5": "&#x201E;"
"_6": "&#x201D;"
"~N": "&#x2116;"
"~w": "&#x00A7;"
"~o": "&#x00B0;"
"_?": "&#x2030;"
"_\"": "&#x2032;"
"~\"": "&#x2033;"
"_'": "&#x2034;"
"~|": "&#x005C;"
"_/": "&#x005F;"
"~/": "&#x007E;"
"~5": "&#x20A4;"
"~c": "&#x00A9;"
"~'": "&#x00AE;"
"~b": "&#x2122;"
"~y": "&#x2640;"
"~z": "&#x2642;"

"_+": "&#x00B1;"
"~x": "&#x00B7;"
"_*": "&#x00D7;"
"~+": "&#x2295;"
"~.": "&#x2299;"
"~*": "&#x2297;"
"~:": "&#x00F7;"
"~V": "&#x221A;"
"_=": "&#x2263;"
"~=": "&#x2248;"
"_;": "&#x2243;"
"~;": "&#x2245;"
"~%": "&#x2260;"
"~?": "&#x2262;"
"_:": "&#x007E;"
"_7": "&#x223E;"
"_<": "&#x2264;"
"~<": "&#x2272;"
"_>": "&#x2265;"
"~>": "&#x2273;"
"~U": "&#x222A;"
"~W": "&#x2229;"
"~Y": "&#x2282;"
"~R": "&#x2286;"
"~Z": "&#x2283;"
"~S": "&#x2287;"
"~e": "&#x2208;"
"~n": "&#x2209;"
"~r": "&#x21D2;"
"_?": "&#x2192;"
"~?": "&#x2190;"
"~Q": "&#x2194;"
"~q": "&#x21D4;"
"~f": "&#x21C4;"
"~H": "&#x21CC;"
"~&": "&#x2191;"
"_&": "&#x2193;"
"~T": "&#x22A5;"
"~P": "&#x2225;"
"_|": "&#x2223;"
"~v": "&#x2228;"
"~u": "&#x2227;"
"~d": "&#x2202;"
"~$": "&#x2207;"
"_$": "&#x2206;"
"~s": "&#x2211;"
"~p": "&#x220F;"
"~I": "&#x222B;"
"~k": "&#x222E;"
"_9": "&#x2205;"
"_8": "&#x221E;"
"~K": "&#x220F;"
"%":  ", "

